version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.11
    steps:
      - checkout

      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup

      - run:
          name: Build
          command: stack --no-terminal build

      - run:
          name: Print stack path
          command: stack path
