version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.11
    steps:
      - checkout

      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - splitbot-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup

      - run:
          name: Build
          command: stack --no-terminal build

      - save_cache:
          name: Cache Dependencies
          key: splitbot-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

  publish_latest:
    docker:
      - image: fpco/stack-build:lts-12.11
    steps:
      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="19.03.4"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build image
          command: |
            TAG=`git describe --tags`
            docker build -f linux/Dockerfile-release -t $DOCKER_IMAGE_NAME:$TAG .

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish_tag:
            requires: [ build ]
            # filters: { tags: { only: /^\d+\.\d+\.\d+/ } }
            filters: { branches: { only: ci-publish-latest } }
