version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.11
    steps:
      - checkout

      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - splitbot-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup

      - run:
          name: Build
          command: stack --no-terminal build

      - save_cache:
          name: Cache Dependencies
          key: splitbot-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

  publish_latest:
    docker:
      - image: fpco/stack-build:lts-12.11
    steps:
      - run:
          name: Build release docker image
          command: echo "Not really!"

workflows:
  version: 2
  master:
    jobs:
      - build
      - publish_latest:
            requires: [ build ]
            filters: { branches: { only: master } }
