version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.11

    steps:
      - checkout

      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - splitbot-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup

      - run:
          name: Build
          command: stack --no-terminal build --copy-bins

      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile-release
            - bin/splitbot

      - save_cache:
          name: Cache Dependencies
          key: splitbot-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

  publish_tag:
    machine: true

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Build image
          command: |
            docker build -f Dockerfile-release -t $DOCKER_IMAGE_NAME .

      - run:
          name: Publish image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$CIRCLE_BRANCH
            docker push $DOCKER_IMAGE_NAME
            docker push $DOCKER_IMAGE_NAME:$CIRCLE_BRANCH

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish_tag:
            requires: [ build ]
            # TODO: USE CIRCLE_TAG instead of CIRCLE_BRANCH
            # filters: { tags: { only: /^\d+\.\d+\.\d+/ } }
            filters: { branches: { only: ci-publish-latest } }
