version: 2.1
executors:
  docker-publisher:
    docker:
      - image: fpco/stack-build:lts-12.11

jobs:
  build:
    executor: docker-publisher

    steps:
      - checkout

      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - splitbot-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup

      - run:
          name: Build
          command: stack --no-terminal build --copy-bins

      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile-release
            - bin/splitbot

      - save_cache:
          name: Cache Dependencies
          key: splitbot-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

  publish_tag:
    executor: docker-publisher

    steps:
      - attach_workspace:
          at: .

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="19.03.4"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build image
          command: |
            docker build -f Dockerfile-release -t $DOCKER_IMAGE_NAME:$CIRCLE_BRANCH	 .

      - run:
          name: Publish image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $DOCKER_IMAGE_NAME:$CIRCLE_BRANCH

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish_tag:
            requires: [ build ]
            # filters: { tags: { only: /^\d+\.\d+\.\d+/ } }
            filters: { branches: { only: ci-publish-latest } }
