resolver: lts-12.11

docker:
  enable: true

system-ghc: true

image:
  container:
    base: "fpco/stack-build:lts-12.11"
    name: "juanedi/splitbot"

ghc-options:
    "$locals": -Wall -fno-warn-name-shadowing -XOverloadedStrings

local-bin-path:
  _build

packages:
- ..
